---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH/img
    - /bin/cp -R css $DEPLOYPATH/css
    - /bin/cp -R barter $DEPLOYPATH/barter
    - /bin/cp -R Tribute $DEPLOYPATH/Tribute
    - /bin/cp -R Sticky $DEPLOYPATH/Sticky
